# .rubocop.yml

# Configuration to disable specific cops
Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Max: 130